### ISSUE TITLE
Disable action workflows for FINDCov19Tracker and enable for  shinyfindapps

### ISSUE THREAD

**Issue by findanna** [dsbbfinddx/FINDCov19Tracker#23]
I have deployed the  shinyfindapps in place of the FINDCov19Tracker, because of an urgent PR.
Please make sure that action workflows do not redeploy the FINDCov19Tracker.

**Comment by benubah** [comment]
@dsbb-finddx Did you disable the workflow for this repo? https://github.com/dsbbfinddx/FINDCov19Tracker/actions
My understanding is that this workflow updates the data daily and if it is disabled, the data stops updating.

I was wondering if the workflow that deploys the Shiny app to shinyapps.io is located in the repo above or within this other repo (https://github.com/dsbbfinddx/FINDCov19TrackerShiny/actions). I see Shiny deployment tasks within the actions here: https://github.com/dsbbfinddx/FINDCov19TrackerShiny/actions

**Comment by findanna** [comment]
@benubah you are right, I re-enabled.

**Comment by benubah** [comment]
I have disabled the other one too. Guess we're safe.
